#!/bin/bash

groupmod -o -g ${PGID} tissue
usermod -o -u ${PUID} tissue

chown -R tissue:tissue /app

umask ${UMASK}

nginx
gosu tissue:tissue /app/.venv/bin/alembic upgrade head && gosu tissue:tissue /app/.venv/bin/uvicorn app.main:app --log-level warning
