"""添加订阅种子信息表

Revision ID: 296fa8c2261d
Revises: 435901486157
Create Date: 2024-06-29 10:49:05.008135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296fa8c2261d'
down_revision: Union[str, None] = '435901486157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.Integer(), nullable=False),
    sa.Column('num', sa.String(), nullable=False),
    sa.Column('is_zh', sa.Boolean(), nullable=False),
    sa.Column('is_uncensored', sa.Boolean(), nullable=False),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('torrent')
    # ### end Alembic commands ###
