"""添加订阅包含和排除关键字

Revision ID: 383104710481
Revises: 9135e6d48625
Create Date: 2025-06-22 10:36:10.116128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383104710481'
down_revision: Union[str, None] = '9135e6d48625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('include_keyword', sa.String(), nullable=True))
    op.add_column('subscribe', sa.Column('exclude_keyword', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribe', 'exclude_keyword')
    op.drop_column('subscribe', 'include_keyword')
    # ### end Alembic commands ###
