"""添加历史记录表

Revision ID: 5df63268ceb5
Revises: 097f5c327430
Create Date: 2024-02-13 12:22:54.896439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df63268ceb5'
down_revision: Union[str, None] = '097f5c327430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('num', sa.String(), nullable=True),
    sa.Column('is_zh', sa.Boolean(), nullable=False),
    sa.Column('is_uncensored', sa.Boolean(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('dest_path', sa.String(), nullable=True),
    sa.Column('trans_method', sa.String(), nullable=False),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
