"""添加站点表

Revision ID: 7c9ba4d939cf
Revises: 383104710481
Create Date: 2025-07-12 14:42:19.800745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9ba4d939cf'
down_revision: Union[str, None] = '383104710481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

site_table = sa.table('site', sa.column('class_str', sa.String), sa.column('priority', sa.Integer))

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_str', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('alternate_host', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(site_table, [
        {'class_str': 'JavBusSpider', 'priority': 1},
        {'class_str': 'JavDBSpider', 'priority': 2},
        {'class_str': 'Jav321Spider', 'priority': 3},
        {'class_str': 'DmmSpider', 'priority': 4},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site')
    # ### end Alembic commands ###
