"""添加订阅状态字段

Revision ID: 9135e6d48625
Revises: 296fa8c2261d
Create Date: 2025-06-21 23:12:32.519524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9135e6d48625'
down_revision: Union[str, None] = '296fa8c2261d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('status', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribe', 'status')
    # ### end Alembic commands ###
