class ErrorCode:
    AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED'
    AUTH_FORBIDDEN = 'AUTH_FORBIDDEN'
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
    REQUEST_FAILED = 'REQUEST_FAILED'

    AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS'

    USER_USERNAME_EXISTS = 'USER_USERNAME_EXISTS'

    VIDEO_NOT_FOUND = 'VIDEO_NOT_FOUND'
    VIDEO_NUMBER_NOT_FOUND = 'VIDEO_NUMBER_NOT_FOUND'
    VIDEO_TRANS_ACROSS_DISK_UNSUPPORTED = 'VIDEO_TRANS_ACROSS_DISK_UNSUPPORTED'

    ACTOR_ALREADY_FAVORITED = 'ACTOR_ALREADY_FAVORITED'
    ACTOR_FAVORITE_NOT_FOUND = 'ACTOR_FAVORITE_NOT_FOUND'
    ACTOR_FAVORITE_SITE_NOT_FOUND = 'ACTOR_FAVORITE_SITE_NOT_FOUND'
    ACTOR_NOT_FOUND = 'ACTOR_NOT_FOUND'

    SITE_NOT_FOUND = 'SITE_NOT_FOUND'
    SITE_TYPE_NOT_FOUND = 'SITE_TYPE_NOT_FOUND'
    SITE_LOGIN_UNSUPPORTED = 'SITE_LOGIN_UNSUPPORTED'
    SITE_LOGIN_PAGE_FAILED = 'SITE_LOGIN_PAGE_FAILED'
    SITE_LOGIN_FAILED = 'SITE_LOGIN_FAILED'
    SITE_ACTOR_UNSUPPORTED = 'SITE_ACTOR_UNSUPPORTED'

    API_KEY_CREATE_FAILED = 'API_KEY_CREATE_FAILED'
    API_KEY_NOT_FOUND = 'API_KEY_NOT_FOUND'
    API_KEY_FORBIDDEN = 'API_KEY_FORBIDDEN'

    SUBSCRIBE_ALREADY_EXISTS = 'SUBSCRIBE_ALREADY_EXISTS'
    SUBSCRIBE_NOT_FOUND = 'SUBSCRIBE_NOT_FOUND'
    SUBSCRIBE_VIDEO_NOT_FOUND = 'SUBSCRIBE_VIDEO_NOT_FOUND'
    SUBSCRIBE_DOWNLOAD_CREATE_FAILED = 'SUBSCRIBE_DOWNLOAD_CREATE_FAILED'

    DOWNLOAD_NUMBER_PARSE_FAILED = 'DOWNLOAD_NUMBER_PARSE_FAILED'
    DOWNLOADER_NOT_CONFIGURED = 'DOWNLOADER_NOT_CONFIGURED'
    DOWNLOADER_CONNECTION_FAILED = 'DOWNLOADER_CONNECTION_FAILED'

    PROVIDER_UNSUPPORTED = 'PROVIDER_UNSUPPORTED'
